version: '3.9'
services:
  postgres:
    container_name: stomble-postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=stomble
      - POSTGRES_PASSWORD=stomble
    ports:
      - '5435:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local